# Generated by Django 2.0.7 on 2018-07-28 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioManager', '0002_userportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='current_price',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='purchase_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
