# Generated by Django 2.0.7 on 2018-07-28 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioManager', '0004_userportfolio_no_of_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='no_of_stocks',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userportfolio',
            name='purchase_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
        ),
    ]
